DSG-1707/Fix-bugs-and-code-smells-reported-by-SonarQube
Nuvalence/dsgov-document-management pull request #106
Opened 2023-09-12 04:27 UTC by afcalderonm

## Description

[___JIRA_TICKET_TITLE___](//jira_url)

## Motivation and Context

## Areas for Focus

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

Patch

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation change (documentation only, will not require redeployment)
- [ ] Refactor or cleanup (functionality unchanged)
  Minor
- [ ] New feature (non-breaking change which adds functionality)
  Major
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have performed a self-review of my own code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

- [ ] I have confirmed all acceptance criteria defined by the story have been met.

2023-09-13 17:12 UTC, dtsong commented
/gcbrun

2023-09-13 17:24 UTC, dtsong commented
/gcbrun

2023-09-14 03:14 UTC, afcalderonm commented
/gcbrun

2023-09-15 01:56 UTC, Ortega-Dan commented on service/src/main/java/io/nuvalence/ds4g/documentmanagement/service/usermanagement/UserManagementClient.java
> +    public void setHttpClient(RestTemplate restTemplate) {
there is no usage on this. Is this really needed?

2023-09-15 02:02 UTC, Ortega-Dan commented on service/src/main/java/io/nuvalence/ds4g/documentmanagement/service/storage/FilesystemStorage.java
> +                || !file.setExecutable(true, true)) {
This class is not really being used right now, and I know this is setting up permissions pretty much for the system user, but ... do we really want to make it executable ? Is it needed in Windows ?

2023-09-15 02:26 UTC, Ortega-Dan commented on service/src/main/java/io/nuvalence/ds4g/documentmanagement/service/util/FileUtils.java
>          }
I am not really sure it is worth adding more code and testing for new exceptions like this, we could try to find common exceptions that are closer to the problem than "RuntimeException" in order to avoid the SQ report, but still are not custom ones since those could be unnecessary. Here we could use "UncheckedIOException" instead.

2023-09-15 02:30 UTC, Ortega-Dan commented on service/src/main/java/io/nuvalence/ds4g/documentmanagement/service/usermanagement/UserManagementClient.java
> +            throw new HttpErrorException("Failed to upload roles: " + response.getStatusCode());
On the same feeling as other comments about possibly not needed custom exceptions (because those may add maintenance burden) can we use a ResponseStatusException here?

2023-09-15 02:31 UTC, Ortega-Dan commented on service/src/main/java/io/nuvalence/ds4g/documentmanagement/service/service/DocumentProcessingSubscriber.java
> +            throw new ParsingException("Error parsing the message from PubSub", ex);
Is it UncheckedIOException better here as well ?

2023-09-15 02:38 UTC, Ortega-Dan commented on service/src/main/java/io/nuvalence/ds4g/documentmanagement/service/config/ApplicationRoleConfig.java
>              }
And could NoSuchElementException better here ?

2023-09-15 02:39 UTC, Ortega-Dan commented on service/src/main/java/io/nuvalence/ds4g/documentmanagement/service/exception/FileProcessingException.java
> +public class FileProcessingException extends RuntimeException {
offered alternatives to this in usage code.

2023-09-15 02:39 UTC, Ortega-Dan commented on service/src/main/java/io/nuvalence/ds4g/documentmanagement/service/exception/HttpErrorException.java
> +public class HttpErrorException extends RuntimeException {
offered alternatives to this in usage code.

2023-09-15 02:39 UTC, Ortega-Dan commented on service/src/main/java/io/nuvalence/ds4g/documentmanagement/service/exception/ParsingException.java
> +public class ParsingException extends RuntimeException {
offered alternatives to this in usage code.

2023-09-15 02:39 UTC, Ortega-Dan commented on service/src/main/java/io/nuvalence/ds4g/documentmanagement/service/exception/RoleConfigurationException.java
> +public class RoleConfigurationException extends RuntimeException {
offered alternatives to this in usage code.

2023-09-15 02:50 UTC, Ortega-Dan commented on service/src/main/java/io/nuvalence/ds4g/documentmanagement/service/entity/DocumentProcessorResult.java
> +    private transient T result;
This is more talking, but I am not sure if this has some implication on the result object being stored, or returned, it is work testing calling the API to see if the result object is both stored and properly returned after adding this (not sure if some tests already cover this)

2023-09-15 03:28 UTC, Ortega-Dan requested changes
Some comments and some changes

2023-09-15 16:12 UTC, afcalderonm commented on service/src/main/java/io/nuvalence/ds4g/documentmanagement/service/storage/FilesystemStorage.java
> +                || !file.setExecutable(true, true)) {
yeah you right, in this case is not need to grant execution permissions, that could be problematic i just remove it

2023-09-15 16:13 UTC, afcalderonm commented on service/src/main/java/io/nuvalence/ds4g/documentmanagement/service/util/FileUtils.java
>          }
yeah you right, it is nos really necessary to cread custom exceptions for this

2023-09-15 16:13 UTC, afcalderonm commented on service/src/main/java/io/nuvalence/ds4g/documentmanagement/service/usermanagement/UserManagementClient.java
> +            throw new HttpErrorException("Failed to upload roles: " + response.getStatusCode());
yeah you right, it is nos really necessary to cread custom exceptions for this i just applied your suggestion

2023-09-15 16:13 UTC, afcalderonm commented on service/src/main/java/io/nuvalence/ds4g/documentmanagement/service/service/DocumentProcessingSubscriber.java
> +            throw new ParsingException("Error parsing the message from PubSub", ex);
yeah you right, it is nos really necessary to cread custom exceptions for this i just applied your suggestion

2023-09-15 16:13 UTC, afcalderonm commented on service/src/main/java/io/nuvalence/ds4g/documentmanagement/service/config/ApplicationRoleConfig.java
>              }
yeah you right, it is nos really necessary to cread custom exceptions for this i just applied your suggestion

2023-09-15 16:15 UTC, afcalderonm commented on service/src/main/java/io/nuvalence/ds4g/documentmanagement/service/entity/DocumentProcessorResult.java
> +    private transient T result;
yeah you right making it transient would carry problems about the result not being stored and dont be able to be returned, and is also not possible to fix because we can make the T Serializable, we have similar problem with the DocumentProcessorResult so i will just ignore this SQ alert and i rollback the change

2023-09-15 16:18 UTC, afcalderonm commented
/gcbrun

2023-09-18 18:17 UTC, Ortega-Dan commented on service/src/main/java/io/nuvalence/ds4g/documentmanagement/service/storage/FilesystemStorage.java
> +                            PosixFilePermissions.fromString("rwx------"));
This line is also setting it excecutable on unix, which is not necessary then.

2023-09-18 18:23 UTC, Ortega-Dan approved these changes
:+1: :shipit:

2023-09-18 18:49 UTC, afcalderonm commented
/gcbrun

2023-09-18 19:07 UTC, Ortega-Dan approved these changes

2023-09-18 19:08 UTC, merged